services:
  app:
    build: .
    container_name: sso_backed_app
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sso_db
      - PORT=3001
      - NODE_ENV=development
      - GOOGLE_CLIENTID=${GOOGLE_CLIENTID}
      - GOOGLE_CLIENTSECRET=${GOOGLE_CLIENTSECRET}
      - GOOGLE_CALLBACKURL=${GOOGLE_CALLBACKURL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15-alpine
    container_name: sso_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sso_db
    ports:
      - '5432:5432'
